Add option to only perform PostgreSQL backup

diff --git a/backup-immich-pg b/backup-immich-pg
--- a/backup-immich-pg
+++ b/backup-immich-pg
@@ -1,4 +1,10 @@
 #!/bin/bash
+#
+# Usage: backup-immich-pg [init|pg]
+# Where:
+#     'backup-immich-pg init' initializes a Borg repository
+#     'backup-immich-pg pg' performs a backup of the Immich PostgreSQL database
+#     'backup-immich-pg' performs both pgsql backup and Borg backup
 
 # Path to Immich library, thumbs, upload
 UPLOAD_LOCATION="/u/Immich"
@@ -32,26 +38,28 @@ else
   docker exec -t immich_postgres pg_dumpall -c -U postgres | \
          gzip > "${UPLOAD_LOCATION}/backups/dump-immich-pg.sql.gz"
 
-  if [ "${have_borgsync}" ]; then
-    borgsync -b create -t ${BORGSYNC_TYPE}
-  else
-    if [ "${have_borg}" ]; then
-      ### Append to local Borg repository
-      borg create ${BACKUP_PATH}/immich-borg::{now} ${UPLOAD_LOCATION} \
-          --exclude ${UPLOAD_LOCATION}/thumbs/ \
-          --exclude ${UPLOAD_LOCATION}/encoded-video/
-      borg prune --keep-weekly=4 --keep-monthly=3 ${BACKUP_PATH}/immich-borg
-      borg compact ${BACKUP_PATH}/immich-borg
-      ### Append to remote Borg repository
-      borg create ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg::{now} \
-          ${UPLOAD_LOCATION} \
-          --exclude ${UPLOAD_LOCATION}/thumbs/ \
-          --exclude ${UPLOAD_LOCATION}/encoded-video/
-      borg prune --keep-weekly=4 --keep-monthly=3 \
-          ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg
-      borg compact ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg
+  [ "$1" == "pg" ] || {
+    if [ "${have_borgsync}" ]; then
+      borgsync -b create -t ${BORGSYNC_TYPE}
     else
-      printf "\nUnable to locate borgsync or borg - no Borg backup created\n"
+      if [ "${have_borg}" ]; then
+        ### Append to local Borg repository
+        borg create ${BACKUP_PATH}/immich-borg::{now} ${UPLOAD_LOCATION} \
+            --exclude ${UPLOAD_LOCATION}/thumbs/ \
+            --exclude ${UPLOAD_LOCATION}/encoded-video/
+        borg prune --keep-weekly=4 --keep-monthly=3 ${BACKUP_PATH}/immich-borg
+        borg compact ${BACKUP_PATH}/immich-borg
+        ### Append to remote Borg repository
+        borg create ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg::{now} \
+            ${UPLOAD_LOCATION} \
+            --exclude ${UPLOAD_LOCATION}/thumbs/ \
+            --exclude ${UPLOAD_LOCATION}/encoded-video/
+        borg prune --keep-weekly=4 --keep-monthly=3 \
+            ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg
+        borg compact ${REMOTE_HOST}:${REMOTE_BACKUP_PATH}/immich-borg
+      else
+        printf "\nUnable to locate borgsync or borg - no Borg backup created\n"
+      fi
     fi
-  fi
+  }
 fi
